version: '3.0'

services: 
    main:
        container_name: main
        build: 
            context: .
        env_file: 
            - .production.env
        ports: [3007:3007]
        command: npm run production
        depends_on: [postgres]
        restart: always
    postgres: 
        container_name: postgres
        image: postgres:12
        environment: 
            PG_DATA: /var/lib/postgresql/data
        ports: [5432:5432]
        volumes: [/var/lib/postgresql/data] 
        restart: always
volumes: 
    pgdata: