name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run npm install
        run: npm install
      - name: Run npm ts-build
        run: npm run ts-build
      - uses: actions/checkout@v2
      - run: |
          git config user.name ${{ secrets.GH_USER }}
          git config user.email "${{ secrets.GH_MAIL }}"
          git add .
          git commit -m "generated"
          git push origin build
