name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run npm install
        run: npm install
      - name: Run npm ts-build
        run: npm run ts-build
      - name: Showing dir
        run: ls
      - uses: actions/checkout@v2
      - run: |
          git config user.name "Utkin Eugeniy"
          git config user.email "utkineugeniy@gmail.com"
          git status
          git add --force .
          git status
          git commit -m "generated"
