name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run npm install
        run: npm install
      - name: Run server app building
        run: npm run ts-build
      - name: Run client app building
        run: npm run dev
      - name: Run git config
        run: |
          git config user.name "Utkin Eugeniy"
          git config user.email "utkineugeniy@gmail.com"
      - name: Run git remote
        run: git remote add buildRepo https://github.com/Horrorspace/ChatApp-deploy
      - name: Run git fetch
        run: git fetch --all
      - name: Run git add
        run: |
          git add --force build
          git add --force .production.env
          git add --force package.json
      - name: Run git commit
        run: git commit -m "generated"
      - name: Run git push
        run: git push buildRepo main
